version: '3.9'

services:
  db_postgres:
    image: postgres:16
    ports: 
      - "5432:5432" 
    restart: "always"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: "example"
      POSTGRES_USER: "exemple"
      POSTGRES_DB: "exemple"

volumes:
  postgres-data:
